defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:16

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install NPM Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Test Suite
          command: npm test

  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Generate .npmrc file
          command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run:
          name: Install NPM Dependencies
          command: npm install
      - run:
          name: Publish to NPM
          command: npm publish --access public

  publish_next:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Generate .npmrc File
          command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run:
          name: Install NPM Dependencies
          command: npm install
      - run:
          name: Publish to NPM
          command: npm publish --tag next --access public

workflows:
  version: 2
  build_test:
      jobs:
        - test:
            filters:
              tags:
                only: /.*/

        - publish:
            requires:
              - test
            filters:
              tags:
                only: /^(v){1}[0-9]+(\.[0-9]+){2}$/
              branches:
                ignore: /.*/

        - publish_next:
            requires:
              - test
            filters:
              tags:
                only: /^(v){1}[0-9]+(\.[0-9]+){2}(-)[0-9]+$/
              branches:
                ignore: /.*/
